version: 2
updates:
  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "python"
    reviewers:
      - "autoblogger-team"
    assignees:
      - "autoblogger-team"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "uvicorn"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]
    groups:
      testing:
        patterns:
          - "pytest*"
          - "*test*"
      security:
        patterns:
          - "cryptography"
          - "pyjwt"
          - "clerk-backend-api"
      ai-ml:
        patterns:
          - "openai"
          - "google-genai"
          - "tavily-python"

  # Frontend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(frontend)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    reviewers:
      - "autoblogger-team"
    assignees:
      - "autoblogger-team"
    ignore:
      # Ignore major version updates for React/Next.js
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      ui:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "tailwindcss"
          - "@tailwindcss/*"
      auth:
        patterns:
          - "@clerk/*"
      tooling:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "typescript"
          - "prettier"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    reviewers:
      - "autoblogger-team"
    assignees:
      - "autoblogger-team"

  # Docker dependencies (if using multi-stage builds)
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "autoblogger-team"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "autoblogger-team"